jswhit/pygrib

setup.cfg.template, setup.py
Now, ECMWF GRIB-API start supporting MSVS (see https://software.ecmwf.int/wiki/pages/viewpage.action?pageId=48109524), so let us start supporting MSVS. 
1. avoid os.sep sensitive (-> use os.path.join)
2. ability to change grib_api library name with setup.cfg
3. editing pyx  to make sense.
4. class _ConfigParser to maintainability
I don't fix 'inttypes.h' problem with MSVS8 (MSVC9), but fix-3 will help us to fix manually.
=> fix for more maintainability and portability (mainly for MSVS):

utils/grib_repack
I am not a `pygrib` user so I am not sure if this fix is desirable. But this was causing failures while trying to package it on Python 3.5.
See https://github.com/conda-forge/pygrib-feedstock/pull/3
=> Changed tab to spaces

g2clib.pyx
The decode$() methods were dividing by 8 when returning the pos using the python '/' operator.  In python3 (for whatever reason) this now "upgrades" the value to a float.  The pos (which is now a float) is used as an index and blows up with a TypeError.
This fix changes the division to a '//' operator which keeps the value as an int.  This should work for all versions of python actually supported by the python developers (2.7+).
=> Fix for python3 (broken index positions)

ncepgrib2.py
GDT 3.32769 is already referenced in the addgrid function.  This adds the reference in the Grib2Decode class initialization.
=> Add support for Arakawa Non-E Staggered Grid 32769

.travis.yml
setup.py says 2.6 is supported, so test it too.
=> Test on Python 2.6

setup.cfg.template, setup.py
Changes to setup.py and setup.cfg.template to provide a mechanism to
either install pygrib or ncepgrib2 or both.
=> choose to install pygrib and/or ncepgrib2

ncepgrib2.py
The comment in the function seems strange since `functools.reduce` exists in python 3. For either python 2 or 3 `functools` would not have been imported on the first execution. And if there was a discrepancy between early versions of python 3 and 2 the code had no handling of such since the code in the except is identical to the one in the try. I'm guessing it was an output of an automated python 2 -> python 3 tool?
I ran the test suite of my change and they passed, I also tested the update against our use of pygrib and our tests passed as well, so it seems the old code didn't do anything.
=> Simplified `_flatten`

ncepgrib2.py
Current version of pygrib emits the following warnings:
```
ncepgrib2.py:1112: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
if gdeflist[n] != []:
ncepgrib2.py:1120: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
if coordlist[n] != []:
```
This changes those lines to make the suggested comparison instead.
I ran the test suite of my change and they passed, I also tested the update against our use of pygrib and our tests passed as well, and the warnings disappeared.
=> Future secure pygrib

pygrib.pyx
removes workarounds added for bugs in older versions of grib-api that led to inaccurate computation of gaussian latitudes under certain conditions.
=> fix for computation of gaussian latitudes #102

ncepgrib2.py, setup.py
Moved import of pygrib.gaulats to inside elif gdtnum == 40 since no other condition relies on gaulats
=> Allow ncepgrib2.Grib2Message.grid() to work without pygrib (except for Gaussian grids)

pygrib.pyx
use floor division operator rather than normal division which always produces a float result
=> use floor division operator

setup.py
Fixes #19. It's not supported on windows. Fixing this allows pygrib to build on Windows.
=> Don't set runtime library directory on windows

setup.py
Add a long description for PyPi, right now it only shows:
> The author of this package has not provided a project description
on PyPi, and I almost passed over this excellent package when looking for a good GRIB package for python, thining it was abandoned or not well maintained. 
I hope to prevent people from making that mistake in the future!
=> Add README.md as long_description for PyPi

.github/workflows/build.yml, .travis.yml, README.md
This migrates the Linux x64 build from Travis-CI to Github Actions.  I noticed that the present Travis-CI builds are not properly using different python versions, whilst this Github Actions one should be.  Python 3.9 was dropped for this PR as there are proj version complications to deal with at a later date.
refs #157
=> migrate Linux x64 CI build to Github Actions

Changelog, src/pygrib/_pygrib.pyx
ensures that gribmessage.__repr__ doesn't fail if shapeOfTheEarth key is missing.
=> fix for issue #177

src/pygrib/_pygrib.pyx
=> address numpy 1.20 builtin deprecations

setup.py
Hi,
I had some trouble installing pygrib on my M1 mac, and i realized that it was because homebrew installs the eccodes in `/opt/homebrew` on [M1 macs](https://docs.brew.sh/Installation).  instead of `/usr/local` on intel macs.
Workaround in the meantime is to use the `ECCODES_DIR` environment variable:
```
export ECCODES_DIR="/opt/homebrew"
```
=> Added eccodes path for M1 macs

Changelog, src/pygrib/_pygrib.pyx, test/test.py
Hi,
This PR enhances `pygrib.open()` to open the path specified by the `pathlib.Path` object.
Although `Path` object has `open()` method, 
Although the `Path` object also has an `open()` method, as noted in #83, pygrib uses C's `fopen()`, so this PR does not use the `open()` method, but simply converts the `Path` object to `str`.
Could you please review this?
It may not be so cool, so if you have a better way to do this, I would appreciate it if you could let me know.
Thanks a lot.
Closes #193.
=> Allow `pygrib.open()` to open the path specified by the Path object

Changelog, MANIFEST.in, src/pygrib/_pygrib.pyx, src/pygrib/portable.h, test/test.py, test/test_open.py
This PR enhances `pygrib.open` to take an `io.BufferedReader` object as an argument.
The `io.BufferedReader` objects are so-called file objects (#83), but I believe file objects also include `io.BytesIO` objects, which reads from Python bytes. In this PR, only reading from `io.BufferedReader` objects, which read from file systems, is supported.
If there is a problem with the following design in the first place, or if there is an implementation problem, I would appreciate it if you could let me know.
Many thanks.
When a user give an `io.BufferedReader` object `f` to `pygrib.open()` instead of the path of the GRIB file, the user usually has done something like `f.read(some_bytes)` or `f.seek(some_pos)` beforehand and thus the position has changed from the start position of the buffer. The …
=> Allow `pygrib.open` to accept an `io.BufferedReader` object

Changelog, src/pygrib/_pygrib.pyx, test/test_misc.py
This PR makes a trivial improvement: changing the type of a message in RuntimeError from `bytes` to `str`.
I don't think `bytes`-type messages will cause much inconvenience in use, but `str`-type messages would be more standard and look better.
About the encoding, I went through [defined error messages](https://github.com/ecmwf/eccodes/blob/develop/src/grib_errors.txt) in ecCodes, and considered that "ascii" would be enough.
Many thanks.
=> Ensure that RuntimeError contains a message of type `str`

src/pygrib/_pygrib.pyx
This fixes up a [compiler error seen on conda-forge](https://github.com/conda-forge/pygrib-feedstock/issues/55) with >=v15 of the Mac compilers, stemming from:
```
src/pygrib/_pygrib.c:44829:3: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'int' [-Wint-conversion]
import_array();
^~~~~~~~~~~~~~
/Users/runner/miniforge3/conda-bld/pygrib_1698064180141/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.10/site-packages/numpy/core/include/numpy/__multiarray_api.h:1545:151: note: expanded from macro 'import_array'
#define import_array() {if (_import_array() < 0) {PyErr_Print(); …
```
=> Fix macOS compile with newer clang

src/pygrib/_pygrib.pyx
I see recent work to support `open()` with `pathlib.Path` objects, which is great! This PR continues to make this support more generic for objects that support the [os.PathLike](https://docs.python.org/3/library/os.html#os.PathLike) protocol. This does, however, require Python 3.6+ (setup.py currently has 2.7, 3.5+, but PyPI has 3.6).
Also use [os.fsencode](https://docs.python.org/3/library/os.html#os.fsencode) to encode the object to a bytes object used internally.
=> Support PathLike file objects

.github/workflows/build-conda.yml, .github/workflows/build-windows.yml, .github/workflows/build.yml
This PR updates `action/checkout` from v2 to v4 to silence warnings on node12 deprecation.
Many thanks.
=> Silence CI warnings on node12 deprecation

.github/workflows/build.yml, .gitignore, README.md, pyproject.toml, setup.cfg, setup.py
This PR moves static project metadata to pyproject.toml, removing setup.cfg and clearing up setup.py a bit.
Also, update a few useful URLs to repo and docs, clean up some old Python version classifiers, add a .gitignore file.
I noticed that [build.yml](https://github.com/jswhit/pygrib/actions/workflows/build.yml) was "disabled manually"; it can be re-enabled, as there was a fix from #223 to make it work. This build is used for the CI status on the README.md page. (Unless another build status should be used instead, suggestions welcome).
=> Move static project metadata to pyproject.toml

Changelog, pyproject.toml, src/pygrib/_pygrib.pyx
This PR fixes `ModuleNotFoundError` resulting from missing dependency on setuptools.
In the executable code of pygrib, setuptools is only used for version comparison purposes, and since setuptools is larger than necessary, this commit replaces it with packaging, which is a more compact module containing reusable core utilities for Python packaging compliant with recent PEPs.
Closes #228.
=> Switch dynamic version handling from pkg_resources (in setuptools) to packaging

src/pygrib/_pygrib.pyx
=> fix logic in setdates

src/pygrib/_pygrib.pyx
NumPy 2.0 prints scalars as np.float(0.0). This reverts to (0.0) for the
time being.
Solves #261
=> Use legacy printing

src/pygrib/_pygrib.pyx
For linux on arm64 the `long` type is not defined, so grab it from `ctypes.c_long`
=> issue265-arm64 from ctypes import c_long as long
